language: python
python:
  - 2.7
addons:
  postgresql: 9.6
env:
  - PLUGIN=payment_cern
  - PLUGIN=ravem
  - PLUGIN=cern_access
before_install:
  - pip install -U pip setuptools
  - pip install https://github.com/indico/indico/archive/${TRAVIS_BRANCH}.zip
  - pip install httpretty
install:
  - '[[ "$PLUGIN" == "ravem" ]] && pip install git+https://github.com/indico/indico-plugins.git@${TRAVIS_BRANCH}#subdirectory=vc_vidyo || :'
  - cd "${TRAVIS_BUILD_DIR}/${PLUGIN}"
  - pip install -e .
script:
  - pytest
notifications:
  email: false
  irc:
    channels:
      - 'chat.freenode.net#indico'
    use_notice: true
    skip_join: true
